Repository tris460/MarketFree, pull requests merged in 2023-06, with the labels that each got.

#37 Login design
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
  src/assets/logo_facebook.png
  src/assets/logo_google.png
Labels: design, web

#40 Product design
  angular.json
  src/app/components/product/product.component.html
  src/app/components/product/product.component.scss
  src/assets/One_Product-Test.jpg
Labels: design, web

#41 Se agregaron las card de todos
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/about/about.component.html
  src/app/components/about/about.component.scss
  src/app/components/about/about.component.ts
  src/assets/BernardoParedes.jpg
  src/assets/BetyMartinez.jpg
  src/assets/LucyGuzman.jpg
  src/assets/SebasGuerra.jpg
Labels: design, web

#42 Design for sell
  src/app/components/sell/sell.component.html
  src/app/components/sell/sell.component.scss
Labels: design, web

#53 Tutorials design
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/tutorials/tutorials.component.html
  src/app/components/tutorials/tutorials.component.scss
  src/app/components/tutorials/tutorials.component.ts
  src/assets/tutorial.pdf
Labels: design, web

#49 Initial design for payment-method
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/faqs/faqs.component.scss
  src/app/components/payment-method/payment-method.component.html
  src/app/components/payment-method/payment-method.component.scss
  src/app/components/payment-method/payment-method.component.ts
Labels: design, web

#48 Initial design for history
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/history/history.component.html
  src/app/components/history/history.component.scss
  src/app/components/history/history.component.ts
Labels: design, web

#47 Help design
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/help/help.component.html
  src/app/components/help/help.component.scss
  src/app/components/help/help.component.ts
  src/app/components/payment/payment.component.html
  src/assets/WhatsApp.png
Labels: design, web

#46 Add initial design for benefits
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/benefits/benefits.component.html
  src/app/components/benefits/benefits.component.scss
  src/app/components/benefits/benefits.component.spec.ts
  src/app/components/benefits/benefits.component.ts
  src/assets/Benefits - Test.jpg
Labels: design, web

#57 rgba instead of hsla
  src/app/components/payment/payment.component.scss
Labels: design

#67 Links
  src/app/components/about/about.component.html
  src/app/components/about/about.component.scss
  src/app/components/benefits/benefits.component.html
  src/app/components/cart/cart.component.html
  src/app/components/faqs/faqs.component.html
  src/app/components/footer/footer.component.html
  src/app/components/header/header.component.html
  src/app/components/help/help.component.html
  src/app/components/help/help.component.scss
  src/app/components/history/history.component.html
  src/app/components/home/home.component.html
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
  src/app/components/payment-method/payment-method.component.html
  src/app/components/payment/payment.component.html
  src/app/components/product/product.component.html
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/components/returns/returns.component.html
  src/app/components/sell/sell.component.html
  src/app/components/tutorials/tutorials.component.html
  src/assets/logo_github.png
Labels: documentation
